language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"

matrix:
  include:
    - node_js: "10"
      cache: npm

jobs:
  include:
    - stage: coverage
      node_js: "10"
      script: npm run codecov
