language: node_js
node_js:
  - "10"
  - "12"

matrix:
  include:
    - node_js: "10"
      cache:
        directories:
          - node_modules

jobs:
  include:
    - stage: coverage
      node_js: "10"
      script: npm run codecov
